- lib/toast.ts
> Adjust docs for persistent toast

- styles/toast.scss
Fixes nextcloud/forms/issues/398
> Fix Dialogs not sticky

- .gitattributes
- package-lock.json
- package.json
- rollup.config.js
> Bundle toastify and transpile it

- README.md
- l10n/messages.pot
- lib/toast.ts
Regression in conflict resolution from #106
See #107  and #111 for discussion.
> Fix permanent displaying

- CHANGELOG.md
- README.md
Closes https://github.com/nextcloud/nextcloud-dialogs/issues/338
> Docs about svg bc break

- README.md
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
> Add npm image to readme

- .github/workflows/changelog-generate.yml
- README.md
Like https://github.com/nextcloud/nextcloud-vue/pull/1818
but I'm unclear how to trigger it, we'll see...
> Add changelog generator workflow action

- CHANGELOG.md
- package-lock.json
- package.json
Tested it on server, seems good for the css side
> 4.0.0-beta.0

- .npmignore
- package.json
<table>
<tr>
<td>Before</td>
<td>After</td>
<tr>
<td>
```
npm notice === Tarball Contents ===
npm notice 39B     .gitattributes
npm notice 8.9kB   CHANGELOG.md
npm notice 35.1kB  LICENSE
npm notice 2.0kB   README.md
npm notice 282B    babel.config.js
npm notice 543B    build/extract-l10n.js
npm notice 1.2kB   dist/filepicker.d.ts
npm notice 5.0kB   dist/index.css
npm notice 392B    dist/index.d.ts
npm notice 275.1kB dist/index.es.js
npm notice 481.6kB dist/index.es.js.map
npm notice 275.6kB dist/index.js
npm notice 481.6kB dist/index.js.map
npm notice 4.5kB   dist/toast.d.ts
npm notice 458B    l10n/ar.pot
npm notice 375B    l10n/ast.pot
npm notice 693B    l10n/br.pot
npm notice 391B    l10n/ca.pot
npm notice 494B    l10n/cs_CZ.pot
npm notice 471B    l10n/cs.pot
npm notice 378B …
```
> Only includes dist folder

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud/nextcloud-dialogs/compare/v4.0.0-beta.1...v4.0.0-beta.2)
- Fix exports [\#699](https://github.com/nextcloud/nextcloud-dialogs/pull/699) ([skjnldsv](https://github.com/skjnldsv))
> 4.0.0-beta.2

- .github/dependabot.yml
- package-lock.json
- package.json
Update the `package.json` to list the currently used packages, no functional change, only to actually see the versions used.
> Pin updated dependencies 

- CHANGELOG.md
- package-lock.json
- package.json
This is just a quick bugfix release.
> chore: Prepare bugfix release 4.2.0-beta.2

- lib/usables/dav.ts
> fix(FilePicker): Request `oc:size` property for showing the file size

- README.md
- l10n/messages.pot
- lib/components/FilePicker/FilePicker.vue
- lib/components/FilePicker/index.ts
- lib/components/types.ts
- lib/filepicker.ts
- lib/index.ts
- lib/toast.ts
- package-lock.json
- package.json
- tsconfig-typedoc.json
<del>:warning: This is based upon #905 so that needs to be merged first!</del>
Fixes Typedoc but also improves the documentation as it adds missing comments.
> Fix documentation generation

- lib/components/FilePicker/FileList.vue
- lib/components/FilePicker/FilePickerBreadcrumbs.vue
Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/921
> [stable4] The table height should be max. 100%

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.0-beta.3...v5.0.0-beta.4)
* fix(FilePicker): Reset selected files if the current directory is changed by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/964
* Revert "fix: Patch `webdav` dependency for invalid `exports` field un… by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/984
> 5.0.0-beta.4

- lib/components/FilePicker/FilePickerBreadcrumbs.vue
Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/987
> [stable4] fix: breadcrumbs grow

- lib/legacy.ts
Fixes https://github.com/nextcloud/server/issues/40545
> [stable24] Bring back the default value for legacy file picker

- l10n/messages.pot
- lib/components/FilePicker/FileList.vue
- lib/components/FilePicker/FileListRow.vue
- lib/components/FilePicker/FilePreview.vue
- lib/index.ts
- lib/usables/preview.ts
- package-lock.json
- package.json
- vite.config.ts
> [stable4] Backport preview generation for FilePicker

- lib/components/FilePicker/FileListRow.vue
- package-lock.json
- package.json
- Bump
- Adapt to breaking changes
Can this be released in beta.5 @susnux ?
> chore: Bump @nextcloud/vue to v8-beta.7

- lib/components/FilePicker/FilePicker.vue
- lib/composables/dav.ts
- package-lock.json
- package.json
> FilePicker: Signal folder creation to files app

- CHANGELOG.md
- package-lock.json
- package.json
Signed-off-by: Louis Chemineau <louis@chmn.me>
> Bump to v5.0.1

- l10n/messages.pot
- lib/components/FilePicker/FilePicker.vue
- lib/components/FilePicker/FilePickerNavigation.vue
- lib/composables/dav.spec.ts
- lib/composables/dav.ts
- lib/composables/filesSettings.spec.ts
- lib/composables/filesSettings.ts
- lib/composables/isPublic.ts
- lib/composables/views.spec.ts
- lib/composables/views.ts
- package-lock.json
- package.json
* Resolves https://github.com/nextcloud/server/issues/42009
Only query settings from the files app when we are on the internal view.
Also adjusted the webdav endpoint used when we are on a public share.
> fix(FilePicker): Allow using on public shares

- CHANGELOG.md
- package-lock.json
- package.json
- tsconfig.json
> chore: Release v6.0.0 for Nextcloud 29+

- lib/components/FilePicker/FilePreview.vue
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2025-01-15 12-48-48](https://github.com/user-attachments/assets/0bd6834d-8674-4502-a2eb-b6c08e496892) | ![Screenshot from 2025-01-15 12-44-49](https://github.com/user-attachments/assets/f9bc5a7b-ba45-491f-a56c-0b544685858a)
> fix(files): Add encrypted icon for end-to-end encrypted folder

- .github/dependabot.yml
- .github/workflows/npm-audit-fix.yml
- README.md
Add information about maintenance of stable branched + add dependabot for stable5 until NC30 is EOL.
> chore: supported branches

- package-lock.json
This audit fix resolves 4 of the total 15 vulnerabilities found in your project.
* [@vue/test-utils](#user-content-\@vue\/test-utils)
* [vite](#user-content-vite)
* [vue-resize](#user-content-vue-resize)
* [vue-template-compiler](#user-content-vue-template-compiler)
* Caused by vulnerable dependency:
* [vue](#user-content-vue)
* [vue-template-compiler](#user-content-vue-template-compiler)
* Affected versions: <=1.3.6
* Package usage:
* `node_modules/@vue/test-utils`
* Vite bypasses server.fs.deny when using ?raw??
* Severity: **moderate** (CVSS 5.3)
* Reference: [https://github.com/advisories/GHSA-x574-m823-4x7w](https://github.com/advisories/GHSA-x574-m823-4x7w)
* Affected versions: 0.11.0 - 6.1.2
* Package usage:
* `node_modules/vite-node/node_modules/vite`
* …
> [stable5] Fix npm audit

- lib/composables/dav.ts
- lib/filepicker-builder.ts
- lib/utils/dav.ts
- package-lock.json
- package.json
* Resolved https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1126
> refactor: do not use Node internals but `@nextcloud/paths` package

- lib/filepicker-builder.ts
> fix: return nodes array from smartpicker

- lib/components/FilePicker/FilePickerBreadcrumbs.vue
- lib/utils/dav.spec.ts
- package-lock.json
This audit fix resolves 1 of the total 3 vulnerabilities found in your project.
* [@nextcloud/eslint-config](#user-content-\\@nextcloud\\/eslint-config)
* Caused by vulnerable dependency:
* [@eslint/json](#user-content-\@eslint\/json)
* Affected versions: 9.0.0-rc.0 - 9.0.0-rc.2
* Package usage:
* `node_modules/@nextcloud/eslint-config`
> [main] Fix npm audit

- lib/toast.ts
> fix: allow dismiss the undo toast
