README.md

You could also add the documentation as "website" in this repository. Then this will be more present.
This may apply to other @nextcloud npm packages as well.

link to documentation

---

lib/toast.ts

This PR contains two fixes:
The documentation for persistent toasts was wrong. Instead of using `timeout=0` you must use a negative number, e.g. `timeout=-1`. See also https://github.com/apvarun/toastify-js/pull/26 .
Toastify-js has a parameter `callback`. This callback function is called when removing the Toast from DOM, see https://github.com/apvarun/toastify-js/blob/1.6.1/src/toastify.js#L233-L245 . Unfortunately, in @nextcloud/dialogs, this parameter was named `onShow` (see https://github.com/nextcloud/nextcloud-dialogs/blob/v1.1.0/lib/toast.ts#L66), which is very misleading. Therefore, this PR renames the parameter and updates the docs.

Toast: fix timeout and callback

---

lib/toast.ts

For https://github.com/nextcloud/server/pull/19346#issuecomment-589629863

Make the Toastify selector configurable

---

lib/toast.ts

Using `body-user` as the default selector caused the Toast to not be usable in guest pages without overriding the selector. An undefined selector selects the body element, so in practice the same element is still selected in logged in pages while making it usable by default in guest pages.
With shame I have to admit that I did not test this before sending the pull request. I just want to go to bed :-P So please test before approving ;-) Thanks!

Make the body element the default Toast selector

---

lib/toast.ts

Ref https://github.com/nextcloud/nextcloud-dialogs/pull/111#issuecomment-614196363
Again, didn't test. If anyone has an application that makes use of this, please give it a quick test.

Allow passing 0 as duration for toasts

---

l10n/messages.pot
lib/index.ts
lib/toast.ts

Fix timeout unit to use the same as toastify.
We also get closer to the syntax of `setTimeout`, let's not mix units in js :see_no_evil: 
___
Allows us to define fancy setTimeouts
```js
import { showUndo, TOAST_UNDO_TIMEOUT } from '@nextcloud/dialogs'
// DELETION
onDeleteWithUndo() {
this.deleted = true
const timeOutDelete = setTimeout(this.onDelete, TOAST_UNDO_TIMEOUT)
showUndo(t('comments', 'Comment deleted'), () => {
clearTimeout(timeOutDelete)
this.deleted = false
})
},
```

Export default undo timeout and fix timeout unit

---

styles/close-dark.svg
styles/toast.scss

Because before this it was black on black and not visible.
Regular:
Hover:

Add dark mode close button

---

styles/toast.scss

Because our modals are on 1000 and we want to see the toast notifications higher: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Modal/Modal.vue#L496

Increase toast z-index above modal dialogs

---

lib/index.ts

Allow users of this package to use the more easily grokked
```ts
getFilePickerBuilder('Choose a file or folder to transfer')
.setType(FilePickerType.Choose)
.build()
```
instead of
```ts
getFilePickerBuilder('Choose a file or folder to transfer')
.setType(1)
.build()
```

Export FilePickerType enum

---

l10n/messages.pot
lib/index.ts
lib/toast.ts
lib/toastify.d.ts
package-lock.json
package.json

Tested with iOS "voice over" and it read the error message now.
Fix #255

Set aria-live default and allow to overwrite it

---

styles/toast.scss

Fix #629 
* 24 👍🏼 
* 25
- Normal
- Keyboard hover
Mode | Nextcloud 24 | Nextcloud 25 (Sorry for the 120% zoom)
---|---|---
Bright mode | ![Bildschirmfoto vom 2022-07-21 12-23-36](https://user-images.githubusercontent.com/213943/180192446-2d5a7b23-d6f6-4570-9e5a-46503077a00b.png) | ![Bildschirmfoto vom 2022-07-21 12-09-18](https://user-images.githubusercontent.com/213943/180192436-241d2471-ec98-4c69-9e34-a73795f95e42.png)
Bright mode keyboard hover | ![Bildschirmfoto vom 2022-07-21 12-23-27](https://user-images.githubusercontent.com/213943/180192448-7f6dbc0d-5f21-478e-849d-16d7a6c39488.png) | ![Bildschirmfoto vom 2022-07-21 12-09-10](https://user-images.githubusercontent.com/213943/180192430-e5630aee-00a9-41ca-b9e9-2d679435a556.png)
Dark mode | ![Bildschirmfoto vom 2022-07-21 …

Fix dark mode with Nextcloud 25

---

.npmignore
README.md
package-lock.json
package.json
rollup.config.js

Found when checking the server's css.
We do not import or copy the assets, which means we're just importing the css without any changes to the url resolving
https://github.com/nextcloud/server/blob/99191167167dd6c98dc3ae9b0eca947526e7939f/core/css/server.scss#L10
By encoding this, we're making sure every release here will works out of the box

Url encode svg and ship it

---

rollup.config.js

Glad we did some beta lol, it seems module do some weird stuff
| Before | After |
|:---------:|:------:|
|![image](https://user-images.githubusercontent.com/14975046/198561222-9132d459-69e8-451f-9a16-68f64037cf2f.png)|![image](https://user-images.githubusercontent.com/14975046/198561070-ee72c93b-ed03-419c-892a-bcf6ab6d532f.png)|
Ref https://github.com/nextcloud/server/pull/34868

Do not change css class names when building

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud/nextcloud-dialogs/compare/v4.0.0-beta.0...v4.0.0-beta.1)
- Do not change css class names when building [\#694](https://github.com/nextcloud/nextcloud-dialogs/pull/694) ([skjnldsv](https://github.com/skjnldsv))

4.0.0-beta.1

---

lib/filepicker.ts
package-lock.json
package.json

Close https://github.com/nextcloud/nextcloud-dialogs/issues/560

Add filepicker filter

---

babel.config.mjs
build/extract-l10n.js
lib/global.d.ts
lib/l10n.ts
package-lock.json
package.json
rollup.config.mjs
tsconfig.json

* This updates rollup to new major 3
* This supersedes #720
* Fixes the script `check-types` to not emit files
* Fixes #696 by allowing tree shaking as the translations are now build in by replacement instead of process environment
The last item is the main reason why I created this PR, as currently builds of apps using `vite` or `rollup` and depending on this package do not work as then `TRANSLATIONS` are bundled like this `({}).TRANSLATIONS.map`.

Update rollup and its dependencies to new major `3.7`

---

package.json
rollup.config.mjs

Currently the *4.0.0* release can not be used with webpack projects, because they will throw:
`ReferenceError: exports is not defined`.
Webpack tries to resolve the import of `@nextcloud/dialogs` to `node_modules/@nextcloud/dialogs/dist/index.js`.
This is a commonjs file, but webpack expects an esm file, so `exports` is not defined.
I guess this happens because `dialogs` has its type set to `module´ so every `.js` file within will be handled as esm.
So to fix this we need to explicitly name commonjs files `.cjs`.
---
I noticed this issue when trying to use `@nextcloud/vue 7.6.0` which depends on dialogs version `4.0.0`.

Fix package resolving in webpack projects

---

.github/workflows/l10n.yml

CI script is not from organization so was not updated, I do not think we need any node 12 scripts anymore.

Update CI for l10n extraction to use node version from `package.json`

---

package.json

Ensure the package can be used with `node16` or `nodeNext` module resolution by adding the types to the `exports` section.

Fix package exports for Typescript projects

---

lib/index.ts
lib/l10n.ts
tsconfig.json

Fixes this error when building:
```
(!) Plugin node-resolve: Could not resolve import "@nextcloud/l10n/dist/gettext" in nextcloud-dialogs/lib/l10n.ts using exports defined in nextcloud-dialogs/node_modules/@nextcloud/l10n/package.json.
(!) Unresolved dependencies
```

fix: Setup Typescript for node16 resolution of `@nextcloud/l10n`

---

babel.config.js
rollup.config.js

Rollup does check strings for full match, so transforming our dependencies list to RegExp will work even with imports like `import 'core-js/foo/bar`.
Before: `1'824 kB` (yes 1.8 MiB)
After: `237 kB`

fix: Make sure dependencies are external

---

CHANGELOG.md
package-lock.json
package.json

Would be great to have the Typescript fixes released, so I prepared the changelog and bumped the package version.
If accepted can someone with admin rights spin the npm release?

Prepare release of version 4.1.0

---

babel.config.js
package-lock.json
package.json

We do not need to include core-js polyfills, they are already bundled with the server core.

chore: Do not bundle `core-js` polyfills already included in server core

---

.github/workflows/changelog-generate.yml
CHANGELOG.md
README.md
package-lock.json
package.json

This also fixed invalid links from moving the library to the new GitHub organization.

chore: Prepare first beta release with FilePicker 4.2.0-beta.1

---

lib/components/FilePicker/FileList.scss
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.vue

Fixing the comment of @jancborchardt about the column alignment. Now only size is end aligned. Also I had to fix overflowing of the name column.
before | after
---|---

fix(FilePicker): Fix design review comments about column alignment

---

lib/components/FilePicker/LoadingTableRow.vue

Adjust color as suggested by @jancborchardt (I can somehow not request a review from you using GH, but feedback is very welcome :wink: ).
I changed the background to
```css
background: linear-gradient(to right,var(--color-background-darker),var(--color-text-maxcontrast),var(--color-background-darker));
background-size: 600px 100%;
border-radius: var(--border-radius);
animation: gradient 12s ease infinite;
```
before | after
---|---

fix(FilePicker): Adjust color of placeholder skeletons

---

l10n/messages.pot
lib/components/DialogBase.vue
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue

Fixing the design review comment by @szaimen 
before | after
---|---

FilePicker: Navigation and filter should be on separate rows on mobile

---

README.md
l10n/messages.pot
lib/components/FilePicker/FileListRow.vue
lib/components/FilePicker/NcDatetime.vue
package-lock.json
package.json

Current Nextcloud 27 and before use nextcloud-vue 7 so for proper support we can not just version 8 in this library as there will be some styling collisions.
So instead lets have a stable4 branch for Nextcloud 27 and below using nextcloud-vue 7 and on master use nextcloud-vue 8 (and set version to dialogs 5.0.0-beta.1).
* Fixes https://github.com/nextcloud-libraries/nextcloud-vue/issues/4418

fix(stable4): Revert nextcloud-vue to version 7.12 to support Nextcloud 27

---

README.md

Documentation of #889 for master / main branch.

docs(README): Add version compatibility section

---

l10n/messages.pot
lib/components/DialogBase.vue
lib/components/FilePicker/FilePickerBreadcrumbs.vue
lib/window.d.ts

* Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/892

[stable4] Backport of the breadcrumbs new button PR

---

lib/filepicker.ts

* Resolves #719 
The file picker builder should support the custom buttons option. Also this changes the file picker builder to use the bundled file picker instead of the global one from the server.
(some linting fixes included (space to tab)).
Changes are kept simple so back porting to stable4 without being a breaking change should be simple.

FilePickerBuilder: Allow to add custom buttons and use shipped picker

---

lib/filepicker.ts

Manual backport of #896 without the breaking change on the `pick` method.

[stable4] Allow to add custom buttons and use shipped picker

---

l10n/messages.pot
lib/components/DialogBase.vue
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePicker.vue

This fixes an issue where the dialog content is scrolled instead of only the file table:
https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/1855448/88a07e7c-d97d-43aa-b65f-1f767af1d9f1
https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/1855448/0071e32e-29dc-4db2-9b61-3df04a9d0310

FilePicker: Ensure only the file table is scrolled

---

l10n/messages.pot
lib/components/DialogBase.vue
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePicker.vue

[stable4] Only scroll file table and not the container

---

CHANGELOG.md

* Release to resolve #887 
- Allow to add custom buttons and use the shipped file picker when using the FilePickerBuilder [\#898](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/898) ([@susnux](https://github.com/susnux))
- Revert `@nextcloud/vue` to version 7.12 to keep supporting Nextcloud 27 [\#889](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/889) ([@susnux](https://github.com/susnux))
- Fix file size is always reported as `0B` in file picker [\#895](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/895) ([@susnux](https://github.com/susnux))
- The file picker breadcrumbs button got a new design [\#894](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/894) ([@susnux](https://github.com/susnux))

chore: Prepare 4.2.0-beta.3

---

l10n/messages.pot
lib/filepicker.ts

<del>:warning: This is based on #903 so merge that one first.</del>
This is version 5 only for #897
It moves the FilePickerBuilder to the native Vue dialog, so some options are changed (breaking API change).

feat!(FilePicker): Modernize `FilePickerBuilder` to directly make use of the Vue based file picker

---

README.md
l10n/messages.pot
lib/components/FilePicker/index.ts
lib/index.ts
lib/toast.ts
package-lock.json
package.json
tsconfig-typedoc.json

docs: Fix typedoc generation and improve documentation of exported member

---

CHANGELOG.md
package-lock.json
package.json

- A Vue based file picker is provided which uses `@nextcloud/vue` version 8, so this library will only work on Nextcloud 28+
- Modernize FilePickerBuilder to directly make use of the Vue based file picker [\#904](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/904) \([@susnux](https://github.com/susnux)\)
- This slightly breaks the FilePickerBuilder API:
- `FilePicker.pick` now returns a Promise resolving to `string[]` containing the picked paths
- `FilePicker.constructor` parameter order was changed
- `FilePickerBuilder.setModal` was removed as it has no effect
- `FilePickerBuilder.setType` is deprecated in favor of `FilePickerBuilder.addButton`
- `FilePickerBuilder.addButton` was added which allows to add custom buttons with callbacks on click (so users can now distinguish …

chore: Prepare release of 5.0.0-beta.1

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePickerBreadcrumbs.vue

If the height is set to 100% the rows are resized and look weird.
before | after
---|---

fix(FilePicker): The table height should be max. 100%

---

l10n/messages.pot
lib/filepicker.ts

Resolves #919 
* Return `string` is multiSelect is false, `string[]` otherwise
* Adjust Typescript interface to infer types correctly, e.g. return type of `pick(): string`
(todo: I still looking for good way to test the typescript interface)

fix(FilePickerBuilder): Revert API change on `pick()`

---

lib/components/FilePicker/FilePickerBreadcrumbs.vue

Stable 4 uses nextcloud-vue version 7.x which had slightly different property names
Part of #920

fix(FilePicker): Fix properties of the `new` button in the breadcrumbs

---

l10n/messages.pot
lib/components/FilePicker/FilePicker.vue

* Part of #920 
If there are no files in the current view or no matching filter, show the empty content component instead of the file list.

Add empty content when there are no files

---

l10n/messages.pot
lib/components/FilePicker/FilePicker.vue

* Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/930

[stable4] feat(FilePicker): Show empty content when there are no files in folder

---

lib/components/FilePicker/FileListRow.vue

Same as the file list of the files app, this now shows the file extension as a trailing text part.

feat(FilePicker): Always show file extension as a trailing text part

---

l10n/messages.pot
lib/components/FilePicker/FileListRow.vue

[stable4] feat(FilePicker): Always show file extension as a trailing text part

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue

fix(FilePicker): Ensure focus-visible outline is visible for all focusable elements

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue

* Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/935

[stable4] fix(FilePicker): Ensure focus-visible outline is visible for all focusable elements

---

l10n/messages.pot
lib/components/FilePicker/FilePicker.vue

Regression of #930 
The filelist should be shown when loading is in progress to show the loading skeletons.

fix: The file list should be showed when files are loading

---

l10n/messages.pot
lib/components/FilePicker/FilePicker.vue

Backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/937

[stable4] fix: The file list should be showed when files are loading

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.vue

Selected file is only displayed by background color and checkboxes are hidden if `multiselect` is `false`.
Part of #920

fix(FilePicker): Do not show checkboxes on single select mode

---

l10n/messages.pot
lib/components/DialogButton.vue
lib/components/FilePicker/FilePicker.vue
lib/components/types.ts
lib/filepicker.ts
lib/svg.d.ts
lib/utils/dialogs.ts
package-lock.json
package.json

* part of #920 
---
* Emit close event when a button is pressed with selected files as payload
* Support button factories which can be used to create reactive buttons (e.g. labels like `move to...`)
* Allow to pass SVGs as icons

feat: Add icons for filepicker and allow reactive button based on current path and selection

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.0-beta.1...v5.0.0-beta.2)
- feat: Add icons for filepicker and allow reactive button based on current path and selection [\#938](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/938) ([susnux](https://github.com/susnux))
- feat\(FilePicker\): Always show file extension as a trailing text part [\#931](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/931) ([susnux](https://github.com/susnux))
- Add empty content when there are no files [\#930](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/930) ([susnux](https://github.com/susnux))
- fix: The file list should be showed when files are loading [\#937](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/937) …

5.0.0-beta.2

---

l10n/messages.pot
lib/components/DialogButton.vue
lib/components/FilePicker/FilePicker.vue
lib/components/types.ts
lib/legacy.ts
lib/svg.d.ts
lib/utils/dialogs.ts
package-lock.json
package.json

Manual backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/938

[stable4] Add icons for filepicker and allow reactive button based on current path and selection 

---

CHANGELOG.md
package-lock.json
package.json

- Add icons for filepicker and allow reactive button based on current path and selection [\#942](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/942) ([@susnux](https://github.com/susnux))
- Always show file extension as a trailing text part [\#933](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/933) ([@susnux](https://github.com/susnux))
- Show empty content when there are no files in folder [\#932](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/932) ([@susnux](https://github.com/susnux))
- Fix properties of the new button in the breadcrumbs [\#928](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/928) ([@susnux](https://github.com/susnux))
- Ensure focus-visible outline is visible for all focusable elements …

chore: Prepare 4.2.0-beta.4

---

lib/legacy.ts

When bundling with webpack (e.g. Nextcloud server) the icons are currently not displayed ("not a svg"), add `?raw` so the icons are included.

[stable4] fix(FilePicker): Fix legacy entry point buttons when bundling with webpack

---

l10n/messages.pot
lib/components/FilePicker/FileList.spec.ts
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.vue
package-lock.json
package.json
patches/webdav+5.2.3.patch
vitest.config.ts

* Also add a default sorting (by name ascending)
* Directories are always sorted first
* Sort by display name if available
Also patch `webdav` dependency for invalid `exports` field until it gets fixed upsteam

fix: Make file list only sortable by one property at the time

---

l10n/messages.pot
lib/filepicker.ts

feat(FilePickerBuilder): Allow to configure the dialog container element

---

l10n/messages.pot
lib/components/FilePicker/FileList.spec.ts
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.vue
package-lock.json
package.json
patches/webdav+5.2.3.patch
vitest.config.ts

* backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/949

[stable4] Make file list only sortable by one property at the time

---

README.md
lib/components/FilePicker/FileList.spec.ts
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.spec.ts
lib/components/FilePicker/FileListRow.vue
vitest.config.ts

Selecting by keyboard was broken due to wrong event and key name.

fix(FilePicker): Fix selecting rows using the keyboard

---

README.md
l10n/messages.pot
lib/components/FilePicker/FileList.spec.ts
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.spec.ts
lib/components/FilePicker/FileListRow.vue
vitest.config.ts

[stable4] Fix FilePicker keyboard handling

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListRow.vue

Fix eslint and one missing import

[stable4] fix: Make eslint happy

---

build/extract-l10n.js
l10n/messages.pot
lib/components/FilePicker/FileListRow.vue
lib/components/FilePicker/FilePreview.vue
lib/usables/preview.spec.ts
lib/usables/preview.ts
package-lock.json
package.json
vite.config.ts

* Use preview controller instead of deprecated OC API
* resolves #943 
* Fallback to MDI 20px icons for files if there is no preview
* part of #920 
* Fix l10n issue: Translations in vue templates were not extracted

fix: Use core preview controller for loading file previews and fallback to MDI icons

---

lib/filepicker.ts
lib/utils/dialogs.ts

and also fix reject if nothing is picked.
* resolves #946 
* resolves #948

fix(FilePickerBuilder): Fix paths returned in Promise by `pick` method

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/LoadingTableRow.vue

fix(FilePicker): Only show checkbox skeletons if multiselect was enabled

---

lib/components/DialogBase.vue
lib/components/FilePicker/FilePickerBreadcrumbs.vue

Stable4 version of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/965

[stable4] Center heading of dialog

---

lib/components/FilePicker/FileList.vue
lib/components/FilePicker/LoadingTableRow.vue

* backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/969

[stable4] fix(FilePicker): Only show checkbox skeletons if multiselect was enabled

---

lib/components/DialogBase.vue
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue

* Resolves #900 
This fixes some remaining styling issues and the second commit sets a fixed height to the file picker.
We already have a max. width of 900px and a max. height of 90% from the modal.
So from my perspective a height of max. 800px looks good (900x800px), thats why I set the height to `min(80vh, 800px)`.
small | medium | large
---|---|---

Fix styling issues and make the FilePicker height fixed

---

l10n/messages.pot
lib/components/FilePicker/FilePicker.vue

* stable4 backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/964

[stable4] fix(FilePicker): Reset selected files if the current directory is change

---

build/extract-l10n.js
l10n/messages.pot

Party backport (the l10n part) of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/962

[stable4] fix(l10n): Extract translations also from vue SFC template attributes

---

CHANGELOG.md
package-lock.json
package.json

* [stable4] fix(FilePicker): Fix legacy entry point buttons when bundling with webpack by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/945
* [stable4] Make file list only sortable by one property at the time by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/951
* [stable4] Fix FilePicker keyboard handling by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/954
* [stable4] fix: Make eslint happy by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/955
* [stable4] Center heading of dialog by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/967
* [stable4] fix(FilePicker): Only show checkbox skeletons if multiselect was enabled by @susnux in …

v4.2.0-beta.5

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.0-beta.1...v5.0.0-beta.2)
* fix: Make file list only sortable by one property at the time by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/949
* fix: styling issues and make the FilePicker height fixed by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/971
* fix: Use core preview controller for loading file previews and fallback to MDI icons by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/962
* fix(FilePicker): Fix selecting rows using the keyboard by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/934
* fix(FilePicker): Only show checkbox skeletons if multiselect was enabled by @susnux in …

5.0.0-beta.3

---

lib/components/FilePicker/FilePicker.vue

Bring back the legacy behavior (which I think makes even more sense).

fix(FilePicker): Reset selected files if the current directory is changed

---

lib/components/FilePicker/FileList.scss
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListIcon.module.scss
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePreview.vue
lib/components/FilePicker/LoadingTableRow.vue
lib/global.d.ts
package-lock.json
package.json
tsconfig.json
vitest.config.ts

* Align navigation and file list on medium and small display sizes
* Align table header for "name" with the file name (previously the preview icon)
(focus on the icon position compared to the name header)
before | after
---|---

Fix alignment of file list

---

lib/usables/dav.spec.ts
lib/usables/dav.ts

We now use the new webdav release, so we can make use of the search function instead of using our patched function.
This simplifies the code a bit :)

fix(FilePicker): Use `search` function from `webdav` package instead of workaround

---

lib/components/FilePicker/FileList.scss
lib/components/FilePicker/FileList.vue
lib/components/FilePicker/FileListIcon.module.scss
lib/components/FilePicker/FileListRow.vue
lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/LoadingTableRow.vue
lib/global.d.ts
package-lock.json
package.json
tsconfig.json
vitest.config.ts

[stable4] Fix table alignment

---

lib/components/DialogBase.vue

Regression of #972 
before | after
---|---

[stable4] fix(Dialog): Make the dialog flex column to show headline on top of content

---

lib/components/FilePicker/FileList.vue

fix(FilePicker): Ensure file list header is shown on top of scrolled content rows

---

lib/components/FilePicker/FileList.vue

backport of https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/997

[stable4] fix(FilePicker): Ensure file list header is shown on top of scrolled content rows

---

lib/filepicker.ts

Avoid logging a console error if no buttons are provided and the default Choose type is used, e.g. when calling in text: 
https://github.com/nextcloud/text/blob/22318ffc88100d6912f586cf2594b65200f4f063/src/components/Editor/MediaHandler.vue#L162-L165

[stable4] Avoid error when not using any custom buttons

---

README.md

As we done for apps, we should also rename for libraries. No need to terms related to slavery. Renaming does not hurt anybody but makes it more inclusive.
E.g.
* https://github.com/nextcloud/text/pull/3671
* https://github.com/nextcloud/forms/pull/1427

chore: Rename development branch to `main`

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.0-beta.4...v5.0.0-beta.5)
* fix: breadcrumbs grow by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/987
* Fix alignment of file list by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/993
* fix(FilePicker): Use `search` function from `webdav` package instead of workaround by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/992
* fix(FilePicker): Ensure file list header is shown on top of scrolled content rows by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/997
* chore(deps): Bump @types/toastify-js from 1.12.0 to 1.12.1 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/10 …

v5.0.0-beta.5

---

lib/components/FilePicker/FileList.vue

fix: Swap sort icons

---

lib/components/FilePicker/FileList.vue

Backport https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1058

[stable4] fix: Swap sort icons

---

l10n/messages.pot
lib/components/FilePicker/FilePickerBreadcrumbs.vue

As per https://github.com/nextcloud/server/issues/37019 the error message should be more specific (it is a folder and not a file)

fix(FilePicker): Make the validity strings more specific

---

CHANGELOG.md
package-lock.json
package.json

* FilePicker: Signal folder creation to files app [\#1095](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1095) ([@susnux](https://github.com/susnux))
* fix: Use `NcDialog` instead of custom dialog component now that it is upstreamed [\#1101](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1101) ([@susnux](https://github.com/susnux))
* Updated dependencies
* Now using stable `@nextcloud/vue` version 8.0.0
* Now using stable `@nextcloud/files` version 3.0.0

Update `@nextcloud/vue` to stable and release v5.0.0

---

lib/components/FilePicker/FilePicker.vue
package-lock.json
package.json

fix(FilePicker): Listen on `update:open` rather than `closed` event from `NcDialog`

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.1...v5.0.2)
* fix(FilePicker): Listen on `update:open` rather than `closed` event from `NcDialog` [\#1113](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1113) ([@susnux](https://github.com/susnux))
* chore(deps): Bump `@nextcloud/vue` from 8.2.0

chore: Release 5.0.2

---

lib/components/FilePicker/FileListRow.vue
lib/components/FilePicker/FilePreview.vue
lib/composables/filesSettings.ts

* Regression of #1108
* Resolves: https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1119
We need to use the property instead of the previous available reference for `cropImagePreviews`.

fix(FilePicker): `cropImagePreviews` is now provided as a prop in FilePreview

---

lib/components/FilePicker/FilePicker.vue

* Resolves: https://github.com/nextcloud/server/issues/41414
Basically also add the current directory as selected node if allowed, otherwise the filepicker builder with reject the promise even if you click "move to" button on the file picker when selecting a folder.

fix(FilePicker): On button click also emit the current directory if `allowPickDirectory` is set to true

---

package-lock.json
package.json
vite.config.ts

Currently, importing raw SVG icons is externalized and used as it is in dist. However, such import is not valid and requires additional bundler configuration. Even when this library doesn't include CSS imports to the bundle.
```js
import IconMove from '@mdi/svg/svg/folder-move.svg?raw'
import IconCopy from '@mdi/svg/svg/folder-multiple.svg?raw'
```
```js
const IconMove = '<svg xmlns="http://www.w3.org/2000/svg" id="mdi-folder-move" viewBox="0 0 24 24"><path d="M14,18V15H10V11H14V8L19,13M20,6H12L10,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V8C22,6.89 21.1,6 20,6Z" /></svg>'
const IconCopy = '<svg xmlns="http://www.w3.org/2000/svg" id="mdi-folder-multiple" viewBox="0 0 24 24"><path d="M22,4H14L12,2H6A2,2 0 0,0 4,4V16A2,2 0 0,0 6,18H22A2,2 0 0,0 24,16V6A2,2 0 0,0 …
```

fix(build): include ?raw data to bundle

---

lib/components/FilePicker/FileList.vue

* Resolves https://github.com/nextcloud/server/issues/42363
given:
```
/
a-folder/
favorite ⭐
```
if you now go to favorites view an click the folder `favorite` the path was set to `/favorite` which is invalid.

fix(FilePicker): Use `Node::path` for current path fixing an clicking favorite folders

---

lib/filepicker-builder.ts

Change error thrown when FilePicker is closed to `FilePickerClosed` so users can distinguish if error or just closed.

enh(FilePickerBuilder): Change error thrown when FilePicker is closed

---

lib/components/FilePicker/FileList.vue

[stable4] fix(FilePicker): Use Node::path for current path fixing an clicking favorite folders

---

l10n/messages.pot
lib/components/FilePicker/FilePickerNavigation.vue

* For https://github.com/nextcloud/server/issues/42599
* See https://github.com/nextcloud/server/issues/42599#issuecomment-1879050422
* Navigation example: https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation.html
🏚️ Before | 🏡 After
No visual changes. Result: no errors through automatically a11y tests.

Remove unneeded `tab`, `tablist` and `aria-selected` roles from navigation

---

l10n/messages.pot
lib/components/FilePicker/FilePreview.vue

It is not allowed to put `aria-label` not on the interactive elements.
Besides this such text isn't nice for screen reader like: "MIME type httpd/unix-directory", "MIME type image/png", "MIME type text/markdown". Would be much better to have just "folder", "document", "image". Some kind of mapping can be done in future (it is not mandatory).  For now removing wrong attribute: https://github.com/nextcloud/server/issues/42626#issuecomment-1881010301

Remove `aria-label` from `<div>`

---

lib/components/FilePicker/FileListRow.spec.ts
lib/components/FilePicker/FileListRow.vue

* Resolves https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1151
This changes two things:
1. The click event on the whole checkbox column is stopped from bubbling
2. Only add the click listener if required, same as the keyboard listener

fix(FilePicker): Stop click event on checkbox column to allow multiselect

---

lib/components/FilePicker/FileList.scss

Fix a visual regression
before | after
---|---

fix(FilePicker): Adjust checkbox position

---

l10n/messages.pot
lib/filepicker-builder.ts

Instead of only showing `Choose FIRST FILE` or just `Choose` show `Choose 3 files` when multiselect is enabled.

fix(FilePicker): Improve choose button text when selecting multiple

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.0.3...v5.1.0)
* enh(FilePickerBuilder): Change error thrown when FilePicker is closed [\#1166](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1166) \([susnux](https://github.com/susnux)\)
* fix(FilePicker): Adjust stylings after migration to `NcDialog` [\#1138](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1138) \([susnux](https://github.com/susnux)\)
* fix(FilePicker): Set default of `path` to undefined to allow using the saved path [\#1137](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1137) \([susnux](https://github.com/susnux)\)
* fix(FilePicker): Use `Node::path` for current path fixing an clicking favorite folders …

chore: Prepare 5.1.0 release

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v4.2.2...v4.2.3)
* fix(FilePicker): Use Node::path for current path fixing an clicking favorite folders [\#1167](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1167) ([susnux](https://github.com/susnux))
* Updated dependencies

chore: Prepare 4.2.3 release

---

lib/components/FilePicker/FilePicker.vue

* Resolves https://github.com/nextcloud/server/issues/42469
If you press a button NcDialog will call the filepicker callback and afterwards close the dialog.
But our callback is async and NcDialog does not await the callback.
This means sometimes the close event with picked nodes is not emitted first but the close from NcDialog.
So what I do now:
1. On button press (now synchronous function) lock the close event
2. Call the callback
3. Emit only one close (that with the picked nodes)
4. Unlock the close event

fix(FilePicker): Stop default close event in case of button press

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.1.0...v5.1.1)
* fix(FilePicker): Stop default close event in case of button press [\#1207](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1207) \([susnux](https://github.com/susnux)\)
* fix(FilePicker): Export `FilePickerClosed` error [\#1198](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1198) \([susnux](https://github.com/susnux)\)
* Updated development dependencies

chore: Prepare 5.1.1 release

---

l10n/ast.pot
l10n/ca.pot
l10n/cs_CZ.pot
l10n/de.pot
l10n/de_DE.pot
l10n/es.pot
l10n/fr.pot
l10n/id.pot
l10n/is.pot
l10n/it.pot
l10n/nb_NO.pot
l10n/nl.pot
l10n/pl.pot
l10n/pt_BR.pot
l10n/ro.pot
l10n/ru.pot
l10n/sr.pot
l10n/sv.pot
l10n/tr.pot
l10n/uk.pot

* Resolves #1211 
```sh
cp -R l10n master-l10n
git checkout stable4
pushd l10n
for f in *; do msgmerge -N $f messages.pot | sed '/^#~/d' | sed '/^$/N;/^\n$/D' > a; mv a $f; done
for f in *; do msgmerge -N ../master-l10n/$f $f | sed '/^#~/d' | sed '/^$/N;/^\n$/D' > a; mv a $f; done
popd
rm -r master-l10n
```
@ostasevych does the translations look right for you?

[stable4] fix(l10n): Update translations from main branch

---

package-lock.json
package.json

Pin version to last resolved version according to lockfile https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/6feaaec5b65ca7295cbf8c6ed9c79a80b238f623/package-lock.json#L3417-L3418
Last updated in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/985
- Checked diff of beta.14 -> beta.21 and seems non-breaking for used APIs
Needed for https://github.com/nextcloud/server/pull/43368

fix: Pin nextcloud/files to last resolved version

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v4.2.4...v4.2.5)
* fix: Pin nextcloud/files to last resolved version [\#1226](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1226) ([Pytal](https://github.com/Pytal))

chore: v4.2.5

---

lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue
lib/usables/dav.ts
lib/usables/isPublic.ts

Manual backport and adjustments for #1241

[stable4] fix public shares

---

CHANGELOG.md
package-lock.json
package.json

Prepare the release, but it would be better to first release the 4.x one and then this one otherwise npmjs will again announce the 4.x release as the latest...

chore: Prepare 5.1.2 release

---

lib/components/FilePicker/FilePicker.vue
lib/components/FilePicker/FilePickerNavigation.vue
lib/filepicker-builder.ts
package-lock.json
package.json

feat: allow to disable file picker navigation

---

lib/composables/dav.ts

* Supersedes https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1284
* Supersedes https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1285
* Resolves https://github.com/nextcloud/server/issues/44482
The propfind was not requesting all needed props, this is fixed by using `davGetDefaultProps` which will then load the file id.

fix(FilePicker): Request all default file props (incl. file id)

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.2.0...v5.2.1)
* fix(FilePicker): Request all default file props (incl. file id) [\#1287](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1287) \([susnux](https://github.com/susnux)\)
* Updated development dependencies
* chore(deps): Bump @nextcloud/files from 3.1.0 to 3.1.1
* chore(deps): Bump webdav from 5.4.0 to 5.5.0

chore: Prepare 5.2.1 release

---

lib/components/GenericDialog.vue
lib/components/types.ts
lib/dialogs.ts
lib/index.ts
lib/utils/dialogs.ts

* Resolves: https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/300 
Lets clean up legacy jQuery UI and move to Vue dialogs.

feat: Provide generic dialogs previously provided by `OC.dialogs`

---

lib/composables/dav.spec.ts
lib/composables/dav.ts
package-lock.json
package.json
vite.config.ts

- Fix https://github.com/nextcloud/server/issues/44613
- Requires https://github.com/nextcloud-libraries/nextcloud-files/pull/923

fix: Fix incorrect directory contents when navigating quickly

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.3.0...v5.3.1)
* fix: Close actions after creating directory and enter it automatically [\#1302](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1302) \([susnux](https://github.com/susnux)\)
* fix: Fix incorrect directory contents when navigating quickly [\#1299](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1299) \([Pytal](https://github.com/Pytal)\)
* Dependency updates

chore: v5.3.1

---

lib/components/FilePicker/FilePreview.vue

* Resolves #1221 
Do not attach image elements for preloading, but just use `new Image()`.

fix(FilePicker): Do not append image preloader to DOM

---

lib/components/FilePicker/FilePicker.vue
lib/components/types.ts
lib/composables/dav.spec.ts
lib/composables/dav.ts

When picking directories and no node is selected the current directory is picked, this is correctly submitted but it is currently not correctly included in the button factory.
Meaning you can for example not check if you can pick the current directory (readonly directory).
Required for https://github.com/nextcloud/server/pull/45688

fix: Also add current folder to button factory

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.3.1...v5.3.2)
* fix: Also add current folder to button factory [\#1351](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1351) \([susnux](https://github.com/susnux)\)
* fix(FilePicker): Do not append image preloader to DOM [\#1340](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1340) \([susnux](https://github.com/susnux)\)
* chore(deps): Bump webdav to 5.6.0
* chore(deps): Bump @nextcloud/router to 3.0.1
* chore(deps): Bump @nextcloud/auth to 2.3.0
* chore(deps): Bump @nextcloud/axios to 2.5.0
* chore(deps): Bump @nextcloud/initial-state to 2.2.0
* chore(deps): Bump @nextcloud/l10n to 3.1.0
* chore(deps): Bump @nextcloud/event-bus to 3.3.1
* chore(deps): …

chore: Prepare release v5.3.2

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.3.2...v5.3.3)
* refactor: `@nextcloud/files` is now aware of public shares also now have `@nextcloud/sharing` [\#1361](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1361) \([susnux](https://github.com/susnux)\)
* Add SPDX header [\#1354](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1354) \([AndyScherzinger](https://github.com/AndyScherzinger)\)
* chore(deps-dev): Bump braces from 3.0.2 to 3.0.3
* chore(deps): Bump @vueuse/core from 10.10.0 to 10.11.0
* chore(deps-dev): Bump sass from 1.77.4 to 1.77.5
* chore(deps-dev): Bump vite from 5.2.13 to 5.3.1

chore: Prepare v5.3.3

---

lib/components/FilePicker/FileList.vue

Vue can not handle `v-for="index in -1"` so ensure the number is positive.

fix: Prevent invalid range for skeleton number

---

lib/components/FilePicker/FilePicker.vue

Allow to use `:path.sync="currentPath"` and fixes regression where changing the folder by clicking a folder in the file list does not navigate to that folder.

fix(FilePicker): Forward update of `currentPath` to `navigatedPath`

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.3.3...v5.3.4)
* fix(FilePicker): Forward update of `currentPath` to `navigatedPath` [\#1370](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1370) \([susnux](https://github.com/susnux)\)
* chore(deps-dev): Bump sass to 1.77.6
* chore(deps-dev): Bump @nextcloud/vite-config to 1.3.0
* chore(deps-dev): Bump happy-dom to 14.12.3
* chore(deps-dev): Bump typedoc to 0.26.0
* chore(deps-dev): Bump typescript to 5.5.2

chore: Prepare v5.3.4

---

lib/components/FilePicker/FilePicker.vue
lib/composables/dav.spec.ts
lib/composables/dav.ts
lib/utils/dav.spec.ts
lib/utils/dav.ts

Instead of fetching the directory in a second request we simply do it like the file app and always request the content together with its root. This also allows to remove some functions by refactoring.

fix(FilePicker): Cleanup DAV handling and properly handle `currentFolder`

---

lib/composables/dav.ts

Regression from the revert. We need to fetch the current folder so we can pick it.
[Bildschirmaufnahme_20240821_121612.webm](https://github.com/user-attachments/assets/42076e7f-ffc2-44f2-ae91-e07c968456d2)
[Bildschirmaufnahme_20240821_121632.webm](https://github.com/user-attachments/assets/3eada178-9c76-4fae-af0a-a96ecc8aa702)

fix: Fetch also current folder in DAV

---

lib/components/FilePicker/FilePreview.vue
lib/composables/preview.ts
lib/utils/imagePreload.ts
package-lock.json
package.json
test/setup.ts
vite.config.ts
vitest.config.ts

* Resolves https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1387
Image preloading should be rate limited, to not overload the server. Now it is set to max. 5 requests at the same time.

feat: Rate-limit image previews

---

REUSE.toml
lib/index.ts
lib/toast.ts
styles/loader.svg
styles/toast.scss

``` ts
const toast = showLoading('Converting files')
// do whatever...
// then
toast.hideToast()
```

feat(toast): add loading toast

---

package-lock.json

This audit fix resolves 17 of the total 26 vulnerabilities found in your project.
* [@nextcloud/files](#user-content-\@nextcloud\/files)
* [@nextcloud/vite-config](#user-content-\@nextcloud\/vite-config)
* [@vitejs/plugin-vue2](#user-content-\@vitejs\/plugin-vue2)
* [@vue/language-core](#user-content-\@vue\/language-core)
* [@vue/test-utils](#user-content-\@vue\/test-utils)
* [cross-spawn](#user-content-cross-spawn)
* [dompurify](#user-content-dompurify)
* [elliptic](#user-content-elliptic)
* [happy-dom](#user-content-happy-dom)
* [micromatch](#user-content-micromatch)
* [nanoid](#user-content-nanoid)
* [rollup](#user-content-rollup)
* [vite](#user-content-vite)
* [vite-plugin-dts](#user-content-vite-plugin-dts)
* [vue-resize](#user-content-vue-resize)
* …

[stable5] Fix npm audit

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v6.0.1...v6.1.0)
* feat(toast): add loading toast by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1554
* feat(files): Add encrypted icon for end-to-end encrypted folder by @JuliaKirschenheuter in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1545
* Fix npm audit by @nextcloud-command in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1502
* Updated development dependencies

chore: 6.1.0

---

lib/toast.ts
styles/toast.scss

For some reasons, it works when I did the screenshots initially.
But it mght have been a caching issue as I tested with hardcoded variables before.
You cannot use css vars for `background-image`
Anyway, this goes back to pure inline svg, and it's much cleaner :rocket:

fix(toast): loading svg

---

CHANGELOG.md
package-lock.json
package.json

[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v6.1.0...v6.1.1)
* fix(toast): loading svg by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1559
* fixed css output file via @nextcloud/vite-config update
* chore(deps): Bump p-queue from 8.0.1 to 8.1.0
* chore(deps-dev): Bump @nextcloud/vite-config from 1.5.0 to 1.5.1
* chore(deps-dev): Bump @vitest/coverage-v8 from 2.1.8 to 3.0.3
* chore(deps-dev): Bump happy-dom from 16.7.1 to 16.7.2
* chore(deps-dev): Bump vite from 6.0.7 to 6.0.9
* chore(deps-dev): Bump vite from 6.0.9 to 6.0.11
* chore(deps-dev): Bump vitest from 2.1.8 to 3.0.3

chore: 6.1.1

---

.env.development
REUSE.toml
test/tsconfig.json
tsconfig.json
vite.config.ts
vitest.config.ts

Fixed issues:
- When building with `dev` we were not enabling vue-devtools. This is fixed by setting `NODE_ENV=development`.
- The tsconfig rootdir was not aligned with the `includes` section. All included files need to be within the root dir. So we now have one config for production code and one for setup and tests.
- The config option "rollup types" will create independent type, this causes the filepicker module to be incompatible with the index module we exported. Fixed by not rolling up types (note: roll up types only works when there is only a single entry point)

chore: simplify vitest config and fix some build issues

---

lib/filepicker-builder.ts

In many places it is useful to have directly access to the nodes as we need to re-fetch them otherwise.
So this allows to reduce web requests :rocket:

feat: allow picking files using the Nextcloud Nodes API

---

lib/components/FilePicker/FileListIcon.module.scss
lib/components/FilePicker/FilePreview.vue

Its now primary with an overlay if needed instead of main text color (and no overlay but plain icon).

fix(file-picker): align folder design with Nextcloud files app

---

lib/dialogs.ts
lib/filepicker-builder.ts
lib/utils/dialogs.ts
lib/vue-shims.d.ts

Regression from https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1681

fix: the nc-vue dialogs function module is called `dialog` not `dialogs`

---

lib/composables/preview.ts

They will all fail with 404 and spam the server.
So we already use folder icons and do not use the result anyways.

perf: do not pre-load folder mime icon

---

CHANGELOG.md

Feature wise this is exactly like v6.2.0
---
This package now builds on top of `@nextcloud/vue` version 9 using Vue 3.
While this package uses Vue 3 it is also possible to use it within a Vue 2 project,
in this case the Vue dependency will not be shared as the dependency was moved from a peer dependency to a plain dependency.
This also means that if you are using Vue 2 you have to ensure you do not use bundler
configurations that enforce resolving Vue to the same version as this will fail now,
instead let the bundler choose the matching Vue version.
For example if using Webpack this will no longer work in **Vue 2** apps:
```js
resolve: {
alias: {
vue$: path.resolve('./node_modules/vue'),
},
}
```
For Vue 3 apps nothing changed, meaning the app and this library will share the same Vue …

chore: prepare release of v7.0.0-rc.0

---

l10n/messages.pot
lib/components/PublicAuthPrompt.vue
lib/index.ts
lib/public-auth.ts
package-lock.json
package.json

[stable6] feat: add guest auth prompt component

---

lib/filepicker-builder.ts

* Resolves https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1773

fix(FilePickerBuilder): correctly return array / plain value depending on multiselect

---

.github/workflows/lint-eslint.yml
lib/components/PublicAuthPrompt.vue
lib/index.ts
lib/public-auth.ts
package.json

Noticed we do not have a linting CI here so we did not notice we merged stuff not complying with ESLint.
So this does:
- Fix code style and logic issues where needed
- Add CI job for ESLint

refactor: adjust code to comply with code style (again)

---

CHANGELOG.md
package-lock.json
package.json

* [stable6] feat: add guest auth prompt component by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1759
* [stable6] fix(FilePickerBuilder): correctly return array / plain value depending on multiselect by @backportbot in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1777
* Updates for project Nextcloud dialogs library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1740
* Updates for project Nextcloud dialogs library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1741
* Update @nextcloud/auth to 2.5.0 by @skjnldsv

chore: v6.3.0

---

CHANGELOG.md
package-lock.json
package.json

* feat: add guest auth prompt by @backportbot in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1760
* fix(FilePickerBuilder): correctly return array / plain value depending on multiselect by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1775
* fix: display guest name validity by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1836
* chore: update to ESLint v9 and apply new rules by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1753
* Updates for project Nextcloud dialogs library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1757
* chore: move from `dev:watch` back to `watch` by @skjnldsv in …

chore: prepare v7.0.0-rc.1

---

CHANGELOG.md
package-lock.json
package.json

* fix: return nodes array from smartpicker by @grnd-alt in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1879
* fix(PublicAuthPrompt): change default notice if identified by @backportbot[bot] in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1880
* Updates for project Nextcloud dialogs library by @transifex-integration[bot] 
* chore(deps): @nextcloud family + various upgrades by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1905
* @grnd-alt made their first contribution in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1879
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v7.0.0-rc.1...v7.0.0-rc.2

chore: v7.0.0-rc.2

---

l10n/messages.pot
lib/components/PublicAuthPrompt.vue
lib/utils/guestNameValidity.spec.ts
lib/utils/guestNameValidity.ts

This is the same limit we apply to authenticated user display names.
The text app stores guest names in a 64 char database field.
Note that this is counting characters - not bytes.
So languages with multi-byte characters can still use 64 chars in name.

fix(guestName): limit length to 64 characters

---

CHANGELOG.md
package-lock.json
package.json

* style(toast): adjust colors for Nextcloud 32 [\#1912](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1912) \([Antreesy](https://github.com/Antreesy)\)
* fix(guestName): limit length to 64 characters [\#1915](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1915) \([max-nextcloud](https://github.com/max-nextcloud)\)
* fix(FilePicker): make move primary and copy secondary [\#1933](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1933) \([susnux](https://github.com/susnux)\)
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v7.0.0-rc.2...v7.0.0-rc.3

chore: release v7.0.0-rc.3

---

l10n/messages.pot
lib/dialogs.spec.ts
lib/dialogs.ts

* resolves https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1526
Often its quite useful to just spin up a very simple dialog without need of using the builder.
(had this floating around for some time, so added tests now and created this PR :) ).

feat(dialogs): allow to quickly show a dialog
